smiles-columns = [smiles, solvent]
batch-size = 10
accelerator = cpu
devices = auto
multi-hot-atom-featurizer-mode = V1
add-h = true
data-path = data/data_all.csv
output-dir = hyperopt/a4a23e92-f43a-479a-877f-44ebcac75cb0
ensemble-size = 1
message-hidden-dim = 280
message-bias = true
depth = 5
dropout = 0.0714895672183328
activation = LEAKYRELU
aggregation = norm
ffn-hidden-dim = 380
ffn-num-layers = 1
target-columns = [peakwavs_max]
splits-column = split
task-type = regression
loss-function = mse
metrics = [mae, rmse]
warmup-epochs = 5
init-lr = 0.0027519340772311877
max-lr = 0.015372150693144746
final-lr = 0.004670032591604472
epochs = 30
data-seed = 123
pytorch-seed = 42
num-workers = 0
rxn-mode = REAC_DIFF
frzn-ffn-layers = 0
aggregation-norm = 100
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08
alpha = 0.1
tracking-metric = val_loss
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-replicates = 1
